export const OBTER_PROJETOS = 'OBTER_PROJETOS';
export const CADASTRAR_PROJETOS = 'CADASTRAR_PROJETOS';
export const ATUALIZA_PROJETO = 'ATUALIZA_PROJETO';
export const DELETAR_PROJETO = 'DELETAR_PROJETO';
