export const OBTER_PROJETOS = 'OBTER_PROJETOS';
export const CADASTRAR_PROJETOS = 'CADASTRAR_PROJETOS';
export const ATUALIZA_PROJETO = 'ATUALIZA_PROJETO';
export const DELETAR_PROJETO = 'DELETAR_PROJETO';

export const OBTER_TAREFAS = 'OBTER_TAREFAS';
export const CADASTRAR_TAREFAS = 'CADASTRAR_TAREFAS';
export const ATUALIZA_TAREFA = 'ATUALIZA_TAREFA';
