export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const ALTERA_PROJETO = 'ALTERA_PROJETO';
export const DELETA_PROJETO = 'DELETA_PROJETO';
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS';

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA';
export const ALTERA_TAREFA = 'ALTERA_TAREFA';

export const NOTIFICAR = 'NOTIFICAR';
